# Generated by Django 4.1.7 on 2023-03-23 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('ISBN', models.CharField(max_length=45)),
                ('genre', models.CharField(choices=[('HORROR', 'Horror'), ('SCIENCE_AND_FICTION', 'Sci-fi'), ('ADVENTURE', 'Adventure'), ('DOCUMENTARY', 'Documentary'), ('ROMANCE', 'Romance')], default=None, max_length=60)),
                ('language', models.CharField(choices=[('ENGLISH', 'Eng'), ('FRENCH', 'Frn'), ('SPANISH', 'Spn'), ('PORTUGUESE', 'Por'), ('YORUBA', 'Yor'), ('DUTCH', 'Dch')], default=None, max_length=75)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_back', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Requested'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='Available', max_length=45)),
                ('imprint', models.CharField(max_length=350)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='book.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.libraryuser')),
            ],
        ),
    ]
