# Generated by Django 4.1.7 on 2023-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_genre_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('NONE', '-choose-'), ('ENGLISH', 'Eng'), ('FRENCH', 'Frn'), ('SPANISH', 'Spn'), ('PORTUGUESE', 'Por'), ('YORUBA', 'Yor'), ('DUTCH', 'Dch')], default='-choose', max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('NONE', '-choose-'), ('HORROR', 'Horror'), ('SCIENCE_AND_FICTION', 'Sci-fi'), ('ADVENTURE', 'Adventure'), ('DOCUMENTARY', 'Documentary'), ('ROMANCE', 'Romance')], default='-choose-', max_length=75),
        ),
    ]
