# Generated by Django 4.1.7 on 2023-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_genre_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('-choose-', 'NONE'), ('Horror', 'HORROR'), ('Sci-fi', 'SCIENCE_AND_FICTION'), ('Adventure', 'ADVENTURE'), ('Documentary', 'DOCUMENTARY'), ('Romance', 'ROMANCE')], default='-choose-', max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('-choose-', 'NONE'), ('Eng', 'ENGLISH'), ('Frn', 'FRENCH'), ('Spn', 'SPANISH'), ('Por', 'PORTUGUESE'), ('Yor', 'YORUBA'), ('Dch', 'DUTCH')], default='-choose-', max_length=75),
        ),
    ]
